// let's create a basic image directly in the code

export const contentType = "image/png";
export const size = { width: 1200, height: 630 };

// Creating a basic static image with just code (no file dependencies)
export default function Image() {
  return new Response(
    '<svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg"><rect width="1200" height="630" fill="#0C0C0C"/><text x="150" y="265" font-family="Arial" font-size="80" fill="#FFFFFF">Invoice</text><text x="150" y="365" font-family="Arial" font-size="40" fill="#AAAAAA">Generated by Midday</text></svg>',
    {
      headers: {
        "Content-Type": "image/svg+xml"
      }
    }
  );
}
